### ISSUE TITLE
need help in using ping command

### ISSUE THREAD

**Issue by ghost** [toni1991/QtMqtt#2]
Thank you for this awesome project.

I've used this project with some modifications into my project.
I wanted to show the mqtt connection status to the server. If it is connected to server it should make visible the connected image and if it is disconnected , it should make visible the disconnected image.

but the problem is, the connection qml page is in different page than the status  image qml page, i've attached both the pages. 

the issue is,
It is connecting to the server from settings.qml
but when I check qmlQmqtt.isConnected()
it does go into the connected area.

**This is from main.qml** (I want the changes here)

```QML
Timer {
        interval: 500; running: true; repeat: true
        onTriggered: {

            if(qmlQmqtt.isConnected())
            {
                con.visible = true
            }
            else {      
                con.visible = false
            }
        }
}

Timer {
    interval: 500; running: true; repeat: true
            onTriggered: {

                if(qmlQmqtt.isConnected())
                {

           dis.visible = false
                }
                else {
                    dis.visible = true
                }
            }
}
```

**this is from settings.qml** the connections are initiated from here

```QML
onClicked: {
    if(qmlQmqtt.isConnected())
    {
        qmlQmqtt.disconnect()
        connbtn.text =  "Connect"
        //              sert.state = "con"
    }
    else
    {
        //         sert.state = "dis"
        Qt.inputMethod.hide();
        if(host.text && port.text)
        {
            qmlQmqtt.host = host.text
            qmlQmqtt.port = port.text
            qmlQmqtt.connect()
            connbtn.text =  "Disonnect"
        }
    }
}
```

I need the connection status in most of the qml pages. and I've no idea how to make it work. I tried for weeks still it didn't work.

**Comment by toni1991** [comment]
I'll give it a quick try later. But as you can maybe see, this project is discontinued since a while and I'm not really into it anymore.

**Comment by ghost** [comment]
Thank You @toni1991 , If you get anything please let me know

**Comment by ghost** [comment]
Hey @toni1991 if you can , help me with one more thing,

I need to change the visibility of an image according to data coming from mqtt broker.

i.e when I manually publish some data like for instance true or false 

- 1. if I publish "mosquitto_pub -t "test" -m "true"

then it should make an image visible or change some value in qml
